spring:
  datasource:
    url: jdbc:mysql://218.241.106.237:3306/hb_sales?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: cnnicdns
  flyway:
    enabled: false
    locations: classpath:db/mysql


  mail:
    host: smtp.163.com
    port: 25
    username: qiangjishen@163.com
    password: TADSRVOHIUOVHJXT
    default-encoding: UTF-8
    forgetPass:
      title: 密码找回服务
      nickname: 塞罕坝地面观测数据共享服务平台
      url: /system/users/pwdreset/resetPassword
    code:
      expired: 30   #code过期时间---分钟
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false


upload:
  #path: /home/project_sjgxpt/dsp/upload/
  path: /home/project_sjgxpt/qjs/upload
  #path: /home/dsp/upload
  #path: d:\tmp